### ISSUE TITLE
Bug when used with another plugin (CSVLint and ComparePlus)

### ISSUE THREAD

**Issue by carlos-esteves** [pnedev/comparePlus#360] opened 2023-07-19 12:34 UTC
After to do "Compare" and stop this there are a "black line" that not disappear from cursor. If I do "Plugins -> CSVLint -> Settings -> Cancel" the BUG (the black line cursor) disappear.

**Comment by pnedev** [comment] 2023-07-19 12:59
Duplicate of https://github.com/pnedev/comparePlus/issues/355 and https://github.com/pnedev/comparePlus/issues/356

You can circumvent that problem by setting `TransparentCurs` CSVLint parameter to `False`. You will find it in CSVLint Settings (at the very bottom). You could also set CSVLint colors (in its Settings) to `Normal (foreground colors)` scheme.

**Closed by pnedev** 2023-07-19 12:59 UTC

**Comment by MagpieFourtyTwo** [comment] 2023-07-21 11:30
Works like a charm - but just after changing both.
THX a lot!
