### ISSUE TITLE
Window does not flash if last diff is blank

### ISSUE THREAD

**Issue by Yaron10** [pnedev/comparePlus#246] opened 2020-07-30 21:49 UTC
Hello Pavel,

Sorry to bother you again. I'd certainly understand and respect it if you preferred to reply some time in the future. :)

**STR:**
Compare [these](https://github.com/pnedev/compare-plugin/files/5003931/pair4.zip) files.
Press `Last`. 
Press `Next`.

**Result:**
The window does not flash.

Thank you.

I wish you the best.

**Comment by pnedev** [comment] 2020-08-03 07:49
Hello Yaron,

Navigation commands have some other issues as well and this was the last thing for me to fix before the new plugin release for a long time (now there are some more ;))
Thanks for reporting it :+1: 

BR

**Comment by Yaron10** [comment] 2020-08-03 13:23
Hello Pavel,

Your work, whenever it's done, is truly appreciated.
And I haven't written it for a long time: ComparePlus is brilliant! :)
:+1: 

BR

**Comment by pnedev** [comment] 2020-08-04 07:40
Thank you, Yaron :)

BR

**Comment by Yaron10** [comment] 2022-07-19 10:59
Hello Pavel,

I've just noticed you've added the "fixed" label to this issue.
Using the files I've attached in the first post here, the case is indeed fixed. 👍 
(I haven't tried it with any other files).

Did you not ping me because you wanted to have another look? Or do you actually consider it "fixed"? 

Thank you very much for your work.

BR

**Comment by pnedev** [comment] 2022-07-19 11:43
Hello Yaron,

The issue is indeed fixed but I didn't ping you because there are some other minor problems related to navigation commands that I'd like to address and keeping this thread open reminds me of them.

BR

**Comment by Yaron10** [comment] 2022-07-19 12:42
Hello Pavel,

👍 

Looking at the issues-tracker now, we can see the light at the end of the tunnel. :)
What an amazing project!
I'm pretty sure ComparePlus is the most complex NPP plugin. In many aspects it's probably more complex than NPP itself.

Thank you.

BR

**Comment by pnedev** [comment] 2022-08-21 21:39
Hello Yaron,

Build https://ci.appveyor.com/project/pnedev/compareplus/builds/44533437 should close all navigation issues I've come across so I'll close this thread as well.

Thank You!

**Closed by pnedev** 2022-08-21 21:39 UTC
Labels: bug, fixed
