### ISSUE TITLE
"Lines above cannot be aligned" after inserting empty lines

### ISSUE THREAD

**Issue by Yaron10** [pnedev/comparePlus#329] opened 2022-10-15 12:15 UTC
Hello Pavel,

Could you please compare [these files](https://github.com/pnedev/comparePlus/files/9792003/menuCmd.zip) (*Ignore Spaces*)?
You get the "Lines above cannot be aligned" message even if you insert an empty line in both files and re-compare.

Thank you for looking into it.

BR

**Comment by pnedev** [comment] 2022-10-18 07:45
Hello Yaron,

I cannot reproduce that either but I know what you are talking about.
I've seen that misbehavior myself but I forgot under what circumstances and I couldn't reproduce it to find exactly the cause.

Thanks for reporting that, I will very much appreciate if you could help me finding a way to reproduce it on my side :+1: 

BR

**Comment by Yaron10** [comment] 2022-10-18 10:40
Hello Pavel,

It depends on NPP window size.
Could you please try it with `<GUIConfig name="AppPosition" x="281" y="3" width="1008" height="735" isMaximized="no" />`?
And check "Ignore Spaces".

_Empty lines are inserted_:
![תמונה](https://user-images.githubusercontent.com/10229320/196405260-8eee4668-c465-4a4c-8e0b-64ca8471d72a.png)

Thank you very much.
BR

**Comment by pnedev** [comment] 2022-10-18 12:43
Hello Yaron,

Perfect :+1: 
I'll look into it, thanks.

BR

**Comment by pnedev** [comment] 2022-10-29 08:42
Hello Yaron,

This issue should be fixed in [this build](https://ci.appveyor.com/project/pnedev/compareplus/builds/45218877).
Very nice catch, thank you :+1: 

BR

**Comment by Yaron10** [comment] 2022-10-29 11:46
Hello Pavel,

👍 
Thank you for your ongoing great work. I appreciate it.

BR

**Comment by Yaron10** [comment] 2022-11-18 16:59
Hello Pavel,

I hope you're doing well.

Could you please compare selections in [these files](https://github.com/pnedev/comparePlus/files/10043253/Test.zip)?
Select all in Test.cpp.
Select from line 622 to line 766 in NppCommands.cpp.

Result:
![תמונה](https://user-images.githubusercontent.com/10229320/202759392-bb9f71f0-c330-42f3-b293-387e98a265e7.png)

Is that expected?

Thank you.
BR

**Comment by pnedev** [comment] 2022-11-19 17:10
Hello Yaron,

I'll check that, thank you.

BR

**Comment by Yaron10** [comment] 2022-11-19 17:35
Hello Pavel,

👍 
Thank you. I appreciate it.

BR

**Comment by pnedev** [comment] 2022-11-21 12:14
Hello again Yaron,

The behavior you observe is expected, yes.
But since my settings had `Align all matching lines` enabled I hit another bug with selection start marking that is fixed now but I'll commit the fix when I check https://github.com/pnedev/comparePlus/issues/334 (that is also alignment problem with last line).
Thanks again.

P.S. I hope you are doing well too :)

BR

**Comment by Yaron10** [comment] 2022-11-21 14:28
Hello Pavel,

Thanks again for your time and work. 👍 

I'm fine. :)

BR

**Comment by pnedev** [comment] 2022-12-13 08:51
Hello Yaron,

The latest master commit should fix the issue with first line alignments.
Please check my comment in https://github.com/pnedev/comparePlus/issues/334 , thanks.

BR

**Closed by pnedev** 2022-12-13 08:51 UTC
Labels: bug, question

**Comment by Yaron10** [comment] 2022-12-13 22:53
Hello Pavel,

Thank you for that too. 👍 

> The behavior you observe is expected, yes.

> The latest master commit should fix the issue with first line alignments.

I'm not quite sure which case should be changed/fixed. :)

BR

**Comment by pnedev** [comment] 2022-12-19 09:41
Hello Yaron,

There was another issue if you do your test selections compare described here but with `Align all matching lines` option enabled. I can't remember details now but it was either that the selections start was not marked properly or the "Above Lines cannot be aligned" message displayed but all lines properly aligned (one of the two).
It is fixed now :)
Thank you.

BR

**Comment by Yaron10** [comment] 2022-12-19 16:14
Hello Pavel,

👍 
Great.
Thanks again.

BR
