### ISSUE TITLE
Equalizer modifies equal lines

### ISSUE THREAD

**Issue by Yaron10** [pnedev/comparePlus#350] opened 2023-03-23 18:31 UTC
Hello Pavel,

It's been some time. I hope you're doing well.

Could you please compare [these files](https://github.com/pnedev/comparePlus/files/11054674/T.zip)?
Ctrl+left-click on the icon in the first line.

Result:
Line 8 is modified.

Thank you.
BR

**Comment by pnedev** [comment] 2023-03-24 09:06
Hello Yaron,

I'm OK, thank you.
I will check that but it might take some time. Thanks for filing the issue.

BR

**Comment by Yaron10** [comment] 2023-03-24 11:08
Hello Pavel,

When you have some free time.
Thank you. I appreciate it. 👍 

BR

**Comment by pnedev** [comment] 2023-04-07 15:56
Hello Yaron,

I hope you are doing OK my friend.

The issue is fixed with [master branch](https://github.com/pnedev/comparePlus/commit/7000740cd563442a3618257928bc4c4bbfcf359d), here are the dev binaries:
 - **[x86](https://ci.appveyor.com/api/buildjobs/c39r04xei642hy7b/artifacts/ComparePlus.dll)**
 - **[x64](https://ci.appveyor.com/api/buildjobs/cpbmc29nojmm4re8/artifacts/ComparePlus.dll)**

I wish you Happy holidays!
BR

**Closed by pnedev** 2023-04-07 15:56 UTC
Labels: bug

**Comment by Yaron10** [comment] 2023-04-08 14:17
Hello my friend Pavel,

Thank you.
I hope you're well too.

And thank you very much for another great fix. I do appreciate your time and work. 👍 
An excellent Fabergé Easter Egg. :)

Happy holidays!

BR
