### ISSUE TITLE
Font Size Reverts to Default after Compare

### ISSUE THREAD

**Issue by umairbinasim** [pnedev/comparePlus#351] opened 2023-03-24 19:53 UTC
Hi,
I am using Compare Plugin v2.0.2 on Notepad++ v8.5 64-bit, running on a Windows 10 Enterprise machine. I have gotten into a habit of keeping my font sizes pretty larger. But every time I use  compare the font size goes to 11ish and then stays that way even after closing the compare. Can we keep it to what was set before running the compare, or revert to original once the compare the is closed.
Thank you.
Regards,
Umair

**Comment by Yaron10** [comment] 2023-03-24 20:09
@umairbinasim,

Could you try ComparePlus?
https://community.notepad-plus-plus.org/topic/23434/new-plugin-compareplus-v1-0-0
https://github.com/pnedev/comparePlus/releases/tag/cp_1.1.0

Regards.

**Comment by pnedev** [comment] 2023-03-27 08:22
Hi @umairbinasim ,

Could you please try ComparePlus 1.1 plugin as @Yaron10 suggested?
Is the problem also present there?

ComparePlus is the successor of Compare plugin - I am no longer supporting Compare plugin.

As a workaround you could open two files, move one of them to other view (select from the menu `View` -> `Move/Clone Current Document` -> `Move to Other View`) and then modify the font size in the new view to be what you want (the default shortcuts for that in Notepad++ are `CTRL` & `+` and `CTRL` & `-`).
Then close the new view (close the file there) and you could restart Notepad++. It should now remember your font size for the other view as well (leading to correct font size during compare as well). It should work regardless of the compare plugin version.

BR

**Comment by pnedev** [comment] 2023-04-19 08:31
@umairbinasim ,

I am closing that issue now because I couldn't reproduce it with ComparePlus plugin.
Nevertheless feel free to write here if you have further comments or need further assistance - I will reopen it again if need be.

BR

**Closed by pnedev** 2023-04-19 08:31 UTC
Labels: question
