### ISSUE TITLE
Some "Equalizer" issues 

### ISSUE THREAD

**Issue by Yaron10** [pnedev/comparePlus#298] opened 2022-07-07 17:37 UTC
Hello Pavel,

Could you please try the following case?

**STR:**
Compare [these files](https://github.com/pnedev/compare-plugin/files/9066086/Find.zip).
Place the caret on line `621` in `FindReplaceDlgOld.cpp`.
_Mouse-scroll_ down to line `631`  in `FindReplaceDlgOld.cpp` and make sure that line `760` in `FindReplaceDlgNew.cpp` is visible.

![תמונה](https://user-images.githubusercontent.com/10229320/177831233-e2bc6998-3230-43df-91db-55ed5dc1636f.png)

Ctrl+left-click on `-` in line `631`.

**Result:**

![תמונה](https://user-images.githubusercontent.com/10229320/177831799-fb1d5ace-88d5-42b4-ae27-968c0a64ac5b.png)

**NOTE:**
If you place the caret on line `631` before Ctrl+left-clicking, the result is OK.

***

Personally, I'd like the caret to be moved to the line whose symbol I Ctrl+left-click.
I consider the "Equalizer" as selecting and pasting.
In pasting the caret would be at the pasted text end. Still, I think it would be nicer if it was placed at the symbol-line.

What do you think?

Thank you.

BR

**Comment by Yaron10** [comment] 2022-07-07 18:05
**NOTE:**
If you place the caret on line `631` before Ctrl+left-clicking, the result is OK.

**Comment by pnedev** [comment] 2022-07-08 08:23
Hello Yaron,

Thanks for the example files and the description.
I'll try that and write back.
I won't have time this weekend so maybe next week, thanks.

BR

**Comment by Yaron10** [comment] 2022-07-08 10:52
Hello Pavel,

Thank you for looking into it, and best of luck.
Whenever you have time, and according to your priority.

BR

**Comment by pnedev** [comment] 2022-07-19 11:34
Hi Yaron,

One question:
Do you think it is better to position the cursor on the clicked line always or only in case the `Following Caret` is enabled?
I intentionally made the cursor to maintain its position on equalize action but in some cases the view is not properly restored as you noticed - I'll fix it soon. I was just wondering about the caret.

Thanks

**Comment by Yaron10** [comment] 2022-07-19 12:42
Hello Pavel,

> or only in case the Following Caret is enabled?

I thought about it when suggesting to move the caret.
It seems like selecting and pasting - caret should be moved regardless of `Following Caret`.
But I'd certainly it if you argued the cases were not quite the same, and users who uncheck `Following Caret` would prefer not to move the caret on equalize.

> but in some cases the view is not properly restored as you noticed - I'll fix it soon.

👍 
Great! I think this is very important.

Thanks again for your work. Much appreciated.

BR

**Comment by pnedev** [comment] 2022-07-19 13:56
Hello again, Yaron,

Could you try with the latest dev branch commit (https://github.com/pnedev/compare-plugin/commit/8da6ae0e635aea7e4d97f62cfc55558174610539) ?
If `Move caret on navigation` is enabled the caret will be set to the beginning of the equalized diff.
The view is now properly restored in both cases (with or without following caret). Auto-recompare must be ON - the problem was manifested on re-compare.

Tell me if you still have concerns or suggestions, thank you very much!

BR

**Comment by Yaron10** [comment] 2022-07-20 19:06
Hello Pavel,

Catching is easier than fixing. And your fix is excellent. 👍 

Thank you for that too.

BR

**Comment by pnedev** [comment] 2022-08-02 20:34
Hi Yaron,

Could you please describe here the minor issue you have come across as you mention in https://github.com/pnedev/comparePlus/issues/307#issuecomment-1202304716 ?

Thank you :+1:

**Comment by Yaron10** [comment] 2022-08-02 21:20
Hello Pavel,

I've encountered a case where the views jump to the wrong position after using the Equalizer.
Unfortunately I don't remember the files, and I'll have to do some tests.
I'm exhausted now and, with your permission, I'll do that tomorrow.

Thank you.

**Comment by pnedev** [comment] 2022-08-03 08:05
Hello Yaron,

OK, when you have time and energy, thank you.

**Comment by Yaron10** [comment] 2022-08-03 10:17
Hello Pavel,

Could you please try the following case?

**STR:**
Compare [these files](https://github.com/pnedev/comparePlus/files/9250332/Find.Modified.zip).
Go to line `5172` in `FindReplaceDlgOld.cpp`.
Ctrl+Left-Click.

![תמונה](https://user-images.githubusercontent.com/10229320/182582521-c8e2fd14-eb6c-4e67-b176-679403b8319c.png)


**Result:**
The inserted block is not visible.

I assume this and the related issues happen even if you call `MakeSureLineIsVisible()` (_I can't remember now the exact function name_).

Thank you again for you time and work. I do appreciate it. 👍 

***

BTW, should Ctrl+Left-Click work in line `5172`?

**Comment by pnedev** [comment] 2022-08-03 15:31
Hello Yaron,

As I wrote in https://github.com/pnedev/comparePlus/issues/307#issuecomment-1204104305 both issues had the same root cause and they should be fixed in https://ci.appveyor.com/project/pnedev/compareplus/builds/44363424 .

> should Ctrl+Left-Click work in line 5172 ?

Strange as it seems it is expected to work that way. This is because the "blank" area after 5172 is considered internally in Scintilla as the line 5172 itself (line annotation is part of the line and cannot exist separately) and if you click on the "blank" (annotation) margin you actually get a click on the line margin itself.
To illustrate this just try setting a bookmark by clicking on the "blank" margin.
Unfortunately there is no reasonable way to circumvent this.

Thank you.

**Closed by pnedev** 2022-08-03 15:31 UTC
Labels: enhancement

**Comment by Yaron10** [comment] 2022-08-03 15:55
Hello Pavel,

👍 
Excellent!
Thank you for the quick fix. Much appreciated.

> Strange as it seems it is expected to work that way.
...
Unfortunately there is no reasonable way to circumvent this.

👍 

Thanks for that as well.
