### ISSUE TITLE
Auto Re-Compare scrolls down to bottom

### ISSUE THREAD

**Issue by AndnixSH** [pnedev/comparePlus#307] opened 2022-07-30 20:22 UTC
Sometimes Re-Compare scrolls way down to bottom when I made some changes, quite annoying to scroll up again and again. I think because there are many differences. I can't show my code or video here at the moment, but I will do if there is anything that can be shown publicly

**Comment by pnedev** [comment] 2022-08-01 07:24
@AndnixSH ,
I was able to recreate it a few times and it is not steadily reproducible - my favorite kind of issues ;)

**Comment by Yaron10** [comment] 2022-08-02 10:28
Hello Pavel,

Thank you for working on these "favorite issues". It's truly appreciated. 👍 

Just wanted to mention that I've encountered again a slimier issue with the "Equalizer".
So the main issue in https://github.com/pnedev/comparePlus/issues/298 is not completely fixed.

**Comment by pnedev** [comment] 2022-08-02 20:46
Hello Yaron,

So @AndnixSH found a ghost and you found a zombie - it's gonna be hell of an evening for me ;)

Could you please check my comment in https://github.com/pnedev/comparePlus/issues/298 ?
Thanks :+1:

**Comment by Yaron10** [comment] 2022-08-02 21:21
Hello Pavel,

You're the Ghosts Buster! :)
I do hope you have a pleasant evening.

Thanks again for your work. 👍

**Comment by pnedev** [comment] 2022-08-03 15:24
Hello guys,

It appeared that the ghost decided to play zombie role as well.
So both issues had one and the same root cause and they should be fixed in https://ci.appveyor.com/project/pnedev/compareplus/builds/44363424 .

Could you please confirm?

Thank you both :+1:

**Comment by Yaron10** [comment] 2022-08-03 15:56
👍

**Closed** 2022-08-04 08:20 UTC
Labels: bug
